"""update users table and dependant foreign keys to app_users

Revision ID: 7f1ef027edd4
Revises: 0ef8e5de6732
Create Date: 2026-01-17 18:41:34.323332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f1ef027edd4'
down_revision: Union[str, None] = '0ef8e5de6732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # app_users changes
    op.drop_index('ix_users_email', table_name='users')
    op.rename_table('users', 'app_users')
    op.add_column('app_users', sa.Column('auth_user_id', sa.String(), nullable=False, server_default='__TEMP_AUTH_USER_ID__'))
    op.alter_column('app_users', 'auth_user_id', server_default=None)
    op.alter_column('app_users', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    existing_nullable=False,
                    server_default=sa.text('now()'))
    op.drop_column('app_users', 'email')
    op.drop_column('app_users', 'password_hash')
    op.execute('ALTER SEQUENCE users_id_seq RENAME TO app_users_id_seq;')
    op.execute('ALTER INDEX users_pkey RENAME TO app_users_pkey;')
    op.execute('ALTER INDEX ix_users_id RENAME TO ix_app_users_id;')
    
    # ai_flashcard_jobs changes
    op.alter_column('ai_flashcard_jobs', 'user_id', new_column_name='app_user_id')
    op.alter_column('ai_flashcard_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               server_default=sa.text('now()'))
    op.alter_column('ai_flashcard_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               server_default=sa.text('now()'))
    op.execute('ALTER INDEX ix_user_id RENAME TO ix_ai_flashcard_jobs_app_user_id;')
    op.execute('ALTER TABLE ai_flashcard_jobs RENAME CONSTRAINT ai_flashcard_jobs_user_id_fkey TO ai_flashcard_jobs_app_user_id_fkey;')

    # notes changes
    op.alter_column('notes', 'user_id', new_column_name='app_user_id')
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.execute('ALTER TABLE notes RENAME CONSTRAINT notes_user_id_fkey TO notes_app_user_id_fkey;')
    
    # study_sessions changes
    op.alter_column('study_sessions', 'user_id', new_column_name='app_user_id')
    op.alter_column('study_sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('study_sessions', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.execute('ALTER TABLE study_sessions RENAME CONSTRAINT study_sessions_user_id_fkey TO study_sessions_app_user_id_fkey;')

    # user_flashcard_progress changes
    op.alter_column('user_flashcard_progress', 'user_id', new_column_name='app_user_id')
    op.execute('ALTER TABLE user_flashcard_progress RENAME CONSTRAINT user_flashcard_progress_user_id_fkey TO user_flashcard_progress_app_user_id_fkey;')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     # --- revert user_flashcard_progress ---
    op.execute('ALTER TABLE user_flashcard_progress RENAME CONSTRAINT user_flashcard_progress_app_user_id_fkey TO user_flashcard_progress_user_id_fkey;')
    op.alter_column('user_flashcard_progress','app_user_id', new_column_name='user_id')
    
    # --- revert study_sessions ---
    op.execute('ALTER TABLE study_sessions RENAME CONSTRAINT study_sessions_app_user_id_fkey TO study_sessions_user_id_fkey;')
    op.alter_column('study_sessions', 'ended_at',
        type_=sa.DateTime(),
        existing_nullable=True)
    op.alter_column('study_sessions', 'started_at',
        type_=sa.DateTime(),
        server_default=None,
        existing_nullable=False)
    op.alter_column('study_sessions', 'app_user_id', new_column_name='user_id')
    
    # --- revert notes ---
    op.execute('ALTER TABLE notes RENAME CONSTRAINT notes_app_user_id_fkey TO notes_user_id_fkey;')
    op.alter_column('notes', 'created_at',
        server_default=None,
        existing_nullable=False)
    op.alter_column('notes', 'app_user_id', new_column_name='user_id')
    
    # --- revert ai_flashcard_jobs ---
    op.execute('ALTER TABLE ai_flashcard_jobs RENAME CONSTRAINT ai_flashcard_jobs_app_user_id_fkey TO ai_flashcard_jobs_user_id_fkey;')
    op.execute('ALTER INDEX ix_ai_flashcard_jobs_app_user_id RENAME TO ix_user_id;')
    op.alter_column('ai_flashcard_jobs', 'updated_at',
        server_default=None,
        existing_nullable=True)
    op.alter_column('ai_flashcard_jobs', 'created_at',
        server_default=None,
        existing_nullable=True)
    op.alter_column('ai_flashcard_jobs', 'app_user_id', new_column_name='user_id')
    
    # --- revert app_users table ---
    op.add_column('app_users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('app_users', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('app_users', 'created_at',
        server_default=None,
        existing_nullable=False)
    op.drop_column('app_users', 'auth_user_id')
    op.execute('ALTER INDEX ix_app_users_id RENAME TO ix_users_id;')
    op.execute('ALTER INDEX app_users_pkey RENAME TO users_pkey;')
    op.execute('ALTER SEQUENCE app_users_id_seq RENAME TO users_id_seq;')
    op.rename_table('app_users', 'users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
