"""add mode and scope columns to study_sessions table

Revision ID: b452c66aaebb
Revises: f3caafb29a8c
Create Date: 2026-01-05 02:47:21.956829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b452c66aaebb'
down_revision: Union[str, None] = 'f3caafb29a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'study_sessions', 
        sa.Column(
            'mode', 
            sa.Enum('flashcards', 'quiz', name='study_mode'), 
            nullable=False, 
            server_default='flashcards',
        ),
    )
    op.add_column(
        'study_sessions', 
        sa.Column(
            'scope', 
            sa.Enum('all', 'note', name='study_scope'), 
            nullable=False,
            server_default='all',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'scope')
    op.drop_column('study_sessions', 'mode')
    # ### end Alembic commands ###
