"""add ai_flashcard_jobs table and relationships in notes and users table to respective foreign keys in ai_flashcard_jobs table

Revision ID: f3caafb29a8c
Revises: 22a59ddd54f3
Create Date: 2025-12-14 21:14:58.062904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3caafb29a8c'
down_revision: Union[str, None] = '22a59ddd54f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_flashcard_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('requested_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_flashcard_jobs_id'), 'ai_flashcard_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_note_id'), 'ai_flashcard_jobs', ['note_id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'ai_flashcard_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_flashcard_jobs_id'), table_name='ai_flashcard_jobs')
    op.drop_index(op.f('ix_note_id'), table_name='ai_flashcard_jobs')
    op.drop_index(op.f('ix_user_id'), table_name='ai_flashcard_jobs')
    op.drop_table('ai_flashcard_jobs')
    # ### end Alembic commands ###
